version: '3.3'

services:
  build:
    hostname: build
    container_name: build
    environment:
      TARGET_OS: ${TARGET_OS}
      ABI: ${ABI}
      MINSDKVERSION: ${MINSDKVERSION}
    image: ghcr.io/udptoolkit/nativebuildimage:main
    stdin_open: true
    tty: true
    volumes:
      - ./:/src
      - ./build_native.sh:/build_native.sh
      - ./build_nuget.sh:/build_nuget.sh
    command: >
      sh -c "cd /src && ./build_native.sh"