name: CI
on: 
  push:
    branches:
      - develop
jobs:
  linux_x64:
    runs-on: ubuntu-latest
    env:
      TARGET_OS: linux
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: docker build
        run: docker-compose up --build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: linux-x64
          path: ./build/${{ env.TARGET_OS }}/*.so

  android_armv7:
    runs-on: ubuntu-latest
    env:
      TARGET_OS: android-armv7
      ABI: armeabi-v7a
      MINSDKVERSION: 24
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: docker build
        run: docker-compose up --build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: android-armv7
          path: ./build/${{ env.TARGET_OS }}/*.so

  android_armv8:
    runs-on: ubuntu-latest
    env:
      TARGET_OS: android-armv8
      ABI: arm64-v8a
      MINSDKVERSION: 24
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: docker build
        run: docker-compose up --build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: android-armv8
          path: ./build/${{ env.TARGET_OS }}/*.so

  win_x64:
    runs-on: ubuntu-latest
    env:
      TARGET_OS: win
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: docker build
        run: docker-compose up --build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: win-x64
          path: ./build/${{ env.TARGET_OS }}/*.dll

  macos:
    runs-on: macos-latest
    env:
      TARGET_OS: macos
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install cmake
        run: brew  install	cmake

      - name: Build
        run: ./build_native.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: mac-x64
          path: ./build/${{ env.TARGET_OS }}/*.dylib
          
  ios:
    if: ${{ false }}  # disable for now
    runs-on: macos-latest
    env:
      TARGET_OS: ios
      APPLE_DEVELOPMENT_TEAM: ${{ secrets.APPLE_DEVELOPMENT_TEAM }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
  
      - name: Install cmake
        run: brew install cmake
  
      - name: Build
        run: ./build_native.sh
  
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: ios
          path: ./build/${{ env.TARGET_OS }}/*.so