name: CI
on: 
  push:
    branches:
      - develop
jobs:
  linux-x64:
    runs-on: ubuntu-latest
    env:
      TARGET_OS: linux
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Build
        run: make build-linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: linux-x64
          path: ./build/${{ env.TARGET_OS }}/*.so

  win-x64:
    runs-on: ubuntu-latest
    env:
      TARGET_OS: win
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install cmake & MinGW
        run: apt-get update && apt-get -y install cmake && apt-get -y install gcc-mingw-w64-x86-64

      - name: Build
        run: make build-win

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: win-x64
          path: ./build/${{ env.TARGET_OS }}/*.dll

  macos:
    runs-on: macos-latest
    env:
      TARGET_OS: macos
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install cmake
        run: brew  install	cmake

      - name: Build
        run: make build-macos

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: mac-x64
          path: ./build/${{ env.TARGET_OS }}/*.dylib

  build_dev_nuget:
    runs-on: ubuntu-latest
    needs: [linux-x64, win-x64, macos]
    env:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '5.0.100'

      - uses: actions/download-artifact@v4
        with:
          name: linux-x64
          path: ./linux-x64

      - uses: actions/download-artifact@v4
        with:
          name: mac-x64
          path: ./mac-x64

      - uses: actions/download-artifact@v4
        with:
          name: win-x64
          path: ./win-x64

      - name: Build nuget
        run: make build-nugets

      - name: Upload Nuget package
        uses: actions/upload-artifact@v4
        with:
          name: UdpToolkitNative
          if-no-files-found: error
          path: ./**/*.nupkg
